language: rust
rust:
 - nightly-2018-01-02

dist: trusty
osx_version: xcode7.3

os:
  - linux
  - osx

git:
  depth: 1

before_script:
  - sudo easy_install virtualenv
  - virtualenv ~/virtualenv
  - source ~/virtualenv/bin/activate

matrix:
  include:
    - script: make wheel
      before_install: HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade node
      env: DEPLOY=mac-wheel
      osx_image: xcode6.4
      os: osx

    - script: make wheel-manylinux IMAGE=quay.io/pypa/manylinux1_x86_64
      env: DEPLOY=linux-x86_64-wheel
      sudo: required
      services:
        - docker

    - script: make wheel-manylinux IMAGE=quay.io/pypa/manylinux1_i686
      env: DEPLOY=linux-x86-wheel
      sudo: required
      services:
        - docker

    - script: make sdist
      env: DEPLOY=sdist

after_success:
  - npm install -g @zeus-ci/cli
  - zeus upload "application/zip+wheel" dist/*

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/2bffb9a6-f612-11e7-abcb-0a580a280587/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
